use dc34_api::*;

/// Standalone ring patterns, selected by `LedManagerOp::SetPattern`.
///
/// These are ordinary phenotypes installed as the gene and expressed, so they reuse the
/// existing renderer rather than adding a second lighting path. Index 0 is not a pattern: it restores gene
/// expression, which stays the default and is the badge's protected behaviour.
///
/// Field meanings, read from the render program (src/bio/lightgenes/main.c), which does not
/// use the Rust field names: `chaser` lands on the C struct's `lin` by byte order.
///
///   cd_period  brightness cycles around the ring; 0 is uniform, higher is more banding
///   cd_rate    0 is FAST and 255 is SLOW - it maps to a cycle length of 0.6s..7s
///   cd_dir     above 128 travels one way, below the other
///   sat        saturation
///   hue_ratedir  low nibble is hue drift rate 0..15; a high nibble above 10 reverses it
///   hue_base/hue_bound  the hue range the ring spans
///   chaser     BELOW 88 overlays a white dot running round the ring; at or above, none
///   nonlin     above 127 squares the brightness curve: dimmer, more contrast
///
/// Two limits worth knowing, both in the renderer and not settable from the gene:
///
///   * There is NO brightness floor. v = 127*(1+cos(spacetime)) passes through zero once per
///     cycle for every LED, and at zero the pixel is black whatever the saturation. Patterns
///     can only keep the RING lit, by giving LEDs different phases (cd_period >= 1) and
///     keeping the cycle quick so each dip is brief. Raising the floor means regenerating
///     lightgenes.rs, which is autogenerated assembly with no build step in this repo.
///
///   * The white dot and the brightness wave run on DIFFERENT clocks: the dot steps once per
///     render frame off loop_state, the wave off tau from the millisecond clock. The dot laps
///     in about 20 frames, quicker than the fastest brightness cycle, so a trailing wave can
///     never track it. comet therefore uses cd_period 0 - a clean dot, no lagging tail.
const PATTERNS: [(&str, Haploid); 9] = [
    // Smooth full-spectrum ring, slow hue drift, no white dot.
    ("rainbow", Haploid {
        cd_period: 0, cd_rate: 200, cd_dir: 200, sat: 255,
        hue_ratedir: 3, hue_base: 0, hue_bound: 255, chaser: 200, nonlin: 100,
    }),
    // Faster hue, and two brightness bands instead of none: with cd_period 0 the whole ring
    // dips to black together once per cycle, which is the fade that was showing up here.
    // Bands put each LED at a different phase, so the dark part travels instead.
    ("rainbow spin", Haploid {
        cd_period: 0, cd_rate: 150, cd_dir: 200, sat: 255,
        hue_ratedir: 12, hue_base: 0, hue_bound: 255, chaser: 200, nonlin: 90,
    }),
    // One brightness wave under the spectrum, twice the speed it was (cd_rate is inverted:
    // lower is faster).
    ("rainbow wave", Haploid {
        cd_period: 1, cd_rate: 45, cd_dir: 200, sat: 255,
        hue_ratedir: 4, hue_base: 0, hue_bound: 255, chaser: 200, nonlin: 110,
    }),
    // The white travelling dot. nonlin above 127 squares the brightness curve, which steepens
    // the falloff behind the dot and shortens the tail.
    ("comet", Haploid {
        cd_period: 4, cd_rate: 100, cd_dir: 200, sat: 255,
        hue_ratedir: 2, hue_base: 140, hue_bound: 200, chaser: 40, nonlin: 100,
    }),
    // One bright point running round the ring.
    ("chase", Haploid {
        cd_period: 1, cd_rate: 40, cd_dir: 200, sat: 255,
        hue_ratedir: 2, hue_base: 150, hue_bound: 190, chaser: 200, nonlin: 100,
    }),
    // Whole ring fading up and down together in a narrow cyan band. The uniform pulse is the
    // point of this one, so cd_period stays 0.
    ("breathe", Haploid {
        cd_period: 0, cd_rate: 240, cd_dir: 0, sat: 220,
        hue_ratedir: 1, hue_base: 120, hue_bound: 140, chaser: 200, nonlin: 90,
    }),
    // Warm amber. Given bands so the ring no longer dips to black all at once, and left
    // linear so it holds mid brightness rather than spending the cycle near zero.
    ("ember", Haploid {
        cd_period: 3, cd_rate: 0, cd_dir: 0, sat: 200,
        hue_ratedir: 1, hue_base: 5, hue_bound: 35, chaser: 200, nonlin: 90,
    }),
    // Light pink shimmer. A high cd_period puts neighbouring LEDs at nearly opposite phase,
    // so they twinkle against each other and the ring is never dark; the low saturation is
    // what makes the pink pale rather than hot.
    ("bird", Haploid {
        cd_period: 5, cd_rate: 60, cd_dir: 200, sat: 225,
        hue_ratedir: 1, hue_base: 218, hue_bound: 236, chaser: 200, nonlin: 90,
    }),
    // Deliberately loud.
    ("riot", Haploid {
        cd_period: 2, cd_rate: 70, cd_dir: 200, sat: 255,
        hue_ratedir: 10, hue_base: 0, hue_bound: 255, chaser: 200, nonlin: 110,
    }),
];

pub const PATTERN_COUNT: usize = PATTERNS.len();

/// Build a Diploid whose `phenotype()` comes out as `p`.
///
/// `phenotype()` blends two strands with dominance rules, so `Diploid([p, p])` does NOT
/// express as `p`: saturating adds pin sat and chaser to 255, and the hue_ratedir rule
/// collapses most inputs to the same value - which made four of the five patterns express
/// almost identically. Each field is inverted here so the pattern that was written is the
/// pattern that renders.
fn as_gene(p: Haploid) -> Diploid {
    let half = p.sat / 2;
    // hue_ratedir is (2 + (14 - min(a+b,14))) % 14; solve for the sum that yields p's value
    let want = p.hue_ratedir % 14;
    let sum = if want >= 2 { 16 - want } else { 16 - (want + 14) };
    // phenotype computes chaser as a.chaser + b.chaser, but nonlin as a.chaser + b.nonlin -
    // the same term feeds both, so they have to be solved together or setting one wrecks the
    // other.
    let a_chaser = p.chaser.min(p.nonlin);
    let a = Haploid {
        cd_period: p.cd_period,
        cd_rate: p.cd_rate,
        cd_dir: p.cd_dir,
        sat: half,
        hue_ratedir: sum.min(14),
        hue_base: p.hue_base,
        hue_bound: p.hue_bound,
        chaser: a_chaser,
        nonlin: 0,
    };
    let b = Haploid {
        cd_period: p.cd_period,
        cd_rate: p.cd_rate,
        cd_dir: 0,
        sat: p.sat - half,
        hue_ratedir: 0,
        hue_base: p.hue_base,
        hue_bound: p.hue_bound,
        chaser: p.chaser - a_chaser,
        nonlin: p.nonlin - a_chaser,
    };
    Diploid([a, b])
}

pub fn start_leds() {
    std::thread::spawn(move || {
        leds();
    });
}

fn leds() {
    let xns = xous_names::XousNames::new().unwrap();

    let sid = xns.register_name(dc34_api::LED_SERVER, None).unwrap();

    #[cfg(not(feature = "uber"))]
    const LED_COUNT: u8 = 10;
    #[cfg(feature = "uber")]
    const LED_COUNT: u8 = 18;

    let mut lightgenes =
        crate::bio::lightgenes::Lightgenes::new(arbitrary_int::u5::new(15), LED_COUNT, None).unwrap();

    let mut rate_param: u8 = 1;
    // The badge's own gene, put aside while a standalone pattern is showing so that
    // selecting "gene (default)" puts back exactly what was there before.
    let mut saved_gene: Option<Diploid> = None;
    let mut msg_opt = None;
    loop {
        xous::reply_and_receive_next(sid, &mut msg_opt).unwrap();
        let opcode = {
            let msg = msg_opt.as_mut().unwrap();
            num_traits::FromPrimitive::from_usize(msg.body.id()).unwrap_or(LedManagerOp::Invalid)
        };
        match opcode {
            LedManagerOp::Autogamy => {
                lightgenes.autogamy();
                lightgenes.express();
            }
            LedManagerOp::SetTestRate => {
                if let Some(scalar) = msg_opt.as_mut().unwrap().body.scalar_message_mut() {
                    rate_param = scalar.arg1.min(255) as u8;
                }
            }
            LedManagerOp::Syngamy => {
                if let Some(scalar) = msg_opt.as_mut().unwrap().body.scalar_message_mut() {
                    if let Some(sperm) = Haploid::deserialize_u32(&[
                        scalar.arg1 as u32,
                        scalar.arg2 as u32,
                        scalar.arg3 as u32,
                        scalar.arg4 as u32,
                    ]) {
                        // rewritten to match exactly what's happening in the production loop
                        let mut egg = lightgenes.meiosis().unwrap();
                        let rate = MutationRate::from_param(rate_param);
                        log::info!("mutate at rate {:?}: {:?}", rate, egg);
                        mutate(&mut egg, rate);
                        log::info!("Mutated {:?}", egg);
                        lightgenes.gene = Some(Diploid([egg, sperm]));
                        lightgenes.express();
                    } else {
                        log::warn!("Couldn't deserialize gene in call to Syngamy, ignoring")
                    }
                }
            }
            LedManagerOp::Force => {
                if let Some(scalar) = msg_opt.as_mut().unwrap().body.scalar_message_mut() {
                    if let Some(phenotype) = Haploid::deserialize_u32(&[
                        scalar.arg1 as u32,
                        scalar.arg2 as u32,
                        scalar.arg3 as u32,
                        scalar.arg4 as u32,
                    ]) {
                        lightgenes.force(phenotype);
                    } else {
                        log::warn!("Couldn't deserialize gene in call to Force, ignoring")
                    }
                }
            }
            LedManagerOp::GeneTest => {
                if let Some(scalar) = msg_opt.as_mut().unwrap().body.scalar_message_mut() {
                    let badge_type = BadgeType::try_from(scalar.arg1 as u8).unwrap_or(BadgeType::None);
                    lightgenes
                        .gene
                        .replace(Diploid([Haploid::from_type(&badge_type), Haploid::from_type(&badge_type)]));
                    log::info!("Init to {:?}: gene {:?}", badge_type, lightgenes.gene);
                    lightgenes.express();
                }
            }
            LedManagerOp::SetGene => {
                if let Some(mem) = msg_opt.as_ref().unwrap().body.memory_message() {
                    lightgenes.gene = Some(Diploid::receive(mem));
                    log::info!("Received gene {:?}", lightgenes.gene);
                    lightgenes.express();
                }
            }
            LedManagerOp::JackEyes => {
                if let Some(scalar) = msg_opt.as_ref().unwrap().body.scalar_message() {
                    lightgenes.jack_eyes(scalar.arg1 != 0);
                }
            }
            LedManagerOp::SetPattern => {
                // scalar_message(), not scalar_message_mut(): the mutable accessor returns
                // None for a plain Scalar and only matches BlockingScalar, so with the
                // fire-and-forget send this server is built around, the body below never ran
                // at all. That is why picking a pattern did nothing, through every earlier
                // attempt at fixing it. JackEyes above uses the same accessor for the same
                // reason.
                if let Some(scalar) = msg_opt.as_ref().unwrap().body.scalar_message() {
                    let sel = scalar.arg1;
                    // Install the pattern AS the gene and express it, exactly the way GeneTest
                    // does. force() writes straight to the engine and left the ring showing
                    // whatever gene expression had already set; express() is the path that
                    // demonstrably drives the ring, so patterns use it too.
                    if sel == 0 {
                        if let Some(gene) = saved_gene.take() {
                            lightgenes.gene = Some(gene);
                        }
                        lightgenes.express();
                        log::info!("LED pattern cleared, gene expression restored");
                    } else if let Some((name, phenotype)) = PATTERNS.get(sel - 1) {
                        if saved_gene.is_none() {
                            saved_gene = lightgenes.gene.clone();
                        }
                        lightgenes.gene = Some(as_gene(*phenotype));
                        lightgenes.express();
                        log::info!("LED pattern {} ({}) selected", sel, name);
                    } else {
                        log::warn!("LED pattern {} out of range, ignoring", sel);
                    }
                }
            }
            LedManagerOp::Pause => {
                if let Some(scalar) = msg_opt.as_mut().unwrap().body.scalar_message_mut() {
                    lightgenes.pause_rendering(scalar.arg1 != 0);
                }
            }
            LedManagerOp::Invalid => {
                log::error!("Invalid LED manager operation: {:?}", opcode);
            }
        };
    }
}
